include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat these as warnings instead of errors
    unused_local_variable: warning
    dead_code: warning